# Generated by Django 4.0.2 on 2022-04-28 15:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Chassis_Corr',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chassis_number', models.IntegerField()),
                ('added_on', models.DateTimeField(blank=True, null=True)),
                ('corr_on', models.DateTimeField(auto_now_add=True)),
                ('unit_number', models.CharField(blank=True, max_length=20, null=True)),
                ('chassis_problem', models.TextField(blank=True, null=True)),
                ('location', models.CharField(blank=True, max_length=20, null=True)),
                ('tag_number', models.IntegerField(blank=True, null=True)),
                ('assignment', models.CharField(blank=True, max_length=20, null=True)),
                ('dmg_img', models.ImageField(blank=True, default='chassis_damages/dmg.jpg', null=True, upload_to='chassis_corr')),
                ('eta', models.DateTimeField(blank=True, null=True)),
                ('repaired_by', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Chassis_number',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chassis_number', models.IntegerField()),
            ],
            options={
                'ordering': ['chassis_number'],
            },
        ),
        migrations.CreateModel(
            name='ContainerType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('containerTypeAndSize', models.CharField(max_length=255, null=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['containerTypeAndSize'],
            },
        ),
        migrations.CreateModel(
            name='Driver',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('driver_name', models.CharField(max_length=255)),
                ('license_number', models.CharField(blank=True, max_length=255, null=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['driver_name'],
            },
        ),
        migrations.CreateModel(
            name='Yard_location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(max_length=255)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['location'],
            },
        ),
        migrations.CreateModel(
            name='TruckingCompany',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=255)),
                ('company_phone', models.IntegerField(blank=True, null=True)),
                ('company_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('company_address', models.TextField(blank=True, null=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['company_name'],
            },
        ),
        migrations.CreateModel(
            name='Truck',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unit_number', models.IntegerField()),
                ('vin', models.CharField(blank=True, max_length=130, null=True)),
                ('plate_number', models.IntegerField(blank=True, null=True)),
                ('year', models.IntegerField(blank=True, null=True)),
                ('make', models.CharField(blank=True, max_length=70, null=True)),
                ('added_on', models.DateTimeField(auto_now_add=True)),
                ('driver', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='dashboard.driver')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['unit_number'],
            },
        ),
        migrations.CreateModel(
            name='Steamship',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shipping_name', models.CharField(max_length=255)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['shipping_name'],
            },
        ),
        migrations.CreateModel(
            name='Prepull',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('container_number', models.CharField(max_length=100)),
                ('container_status', models.CharField(choices=[('na', 'N/A'), ('load', 'Load'), ('empty', 'Empty')], default='na', max_length=6)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('delivery_date', models.DateTimeField(blank=True, null=True)),
                ('inbound_date_lt', models.DateTimeField(blank=True, null=True)),
                ('inbound_date_gt', models.DateTimeField(blank=True, null=True)),
                ('destination', models.CharField(blank=True, choices=[('highway', 'Highway'), ('local', 'Local')], max_length=7, null=True)),
                ('weight', models.PositiveBigIntegerField(blank=True, null=True)),
                ('weight_type', models.CharField(blank=True, choices=[('kg', 'KILLOGRAMS'), ('lbs', 'LBS')], max_length=10, null=True)),
                ('comments', models.TextField(blank=True, null=True)),
                ('containerType', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='dashboard.containertype')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['container_number'],
            },
        ),
        migrations.CreateModel(
            name='Gatecheck',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('IN', 'IN'), ('OUT', 'OUT')], max_length=3, null=True)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('trucking_company', models.CharField(choices=[('0', 'N/A'), ('trump transport', 'TRUMP TRANSPORT')], default='trump transport', max_length=20, null=True)),
                ('outer_company_manual', models.CharField(blank=True, max_length=100, null=True)),
                ('manual_truck_number', models.CharField(blank=True, max_length=20, null=True)),
                ('container_number', models.CharField(blank=True, max_length=50, null=True)),
                ('chassis_number', models.CharField(blank=True, max_length=20, null=True)),
                ('comments', models.TextField(blank=True, null=True)),
                ('outer_company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='dashboard.truckingcompany')),
                ('truck_number', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='dashboard.truck')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Container_in_gate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('container_number', models.CharField(max_length=100)),
                ('container_plug_check', models.CharField(blank=True, choices=[('na', 'N/A'), ('in', 'Plugged In'), ('out', 'Plugged Out')], default='na', max_length=3, null=True)),
                ('yard_location', models.CharField(max_length=100, null=True)),
                ('container_status', models.CharField(choices=[('na', 'N/A'), ('load', 'Load'), ('empty', 'Empty')], default='na', max_length=6)),
                ('booking_number', models.CharField(blank=True, max_length=100, null=True)),
                ('seal_number', models.CharField(blank=True, max_length=100, null=True)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('delivery_date', models.DateTimeField(blank=True, null=True)),
                ('destination', models.CharField(blank=True, choices=[('highway', 'Highway'), ('local', 'Local')], max_length=7, null=True)),
                ('weight', models.PositiveBigIntegerField(blank=True, null=True)),
                ('weight_type', models.CharField(blank=True, choices=[('kg', 'KILLOGRAMS'), ('lbs', 'LBS')], max_length=10, null=True)),
                ('trucking_company', models.CharField(choices=[('0', 'N/A'), ('trump transport', 'TRUMP TRANSPORT')], default='trump transport', max_length=20, null=True)),
                ('outer_company_manual', models.CharField(blank=True, max_length=100, null=True)),
                ('manual_truck_number', models.CharField(blank=True, max_length=20, null=True)),
                ('chassis_number', models.CharField(blank=True, max_length=20, null=True)),
                ('comments', models.TextField(blank=True, null=True)),
                ('containerType', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='dashboard.containertype')),
                ('outer_company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='dashboard.truckingcompany')),
                ('steamshiping_line', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='dashboard.steamship')),
                ('truck_number', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='dashboard.truck')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['container_number'],
            },
        ),
        migrations.CreateModel(
            name='Container_gate_out',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('container_number', models.CharField(blank=True, max_length=100, null=True)),
                ('trucking_company', models.CharField(choices=[('0', 'N/A'), ('trump transport', 'TRUMP TRANSPORT')], default='trump transport', max_length=20, null=True)),
                ('outer_company_manual', models.CharField(blank=True, max_length=100, null=True)),
                ('manual_truck_number', models.IntegerField(blank=True, null=True)),
                ('chassis_number', models.CharField(blank=True, max_length=20, null=True)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('comments', models.TextField(blank=True)),
                ('in_gate_user', models.CharField(blank=True, max_length=20, null=True)),
                ('containerType', models.CharField(blank=True, max_length=20, null=True)),
                ('container_plug_check', models.CharField(blank=True, max_length=20, null=True)),
                ('yard_location', models.CharField(blank=True, max_length=20, null=True)),
                ('container_status', models.CharField(blank=True, max_length=20, null=True)),
                ('booking_number', models.CharField(blank=True, max_length=100, null=True)),
                ('seal_number', models.CharField(blank=True, max_length=100, null=True)),
                ('enter_date', models.DateTimeField(blank=True, null=True)),
                ('delivery_date', models.DateTimeField(blank=True, null=True)),
                ('destination', models.CharField(blank=True, max_length=20, null=True)),
                ('weight', models.PositiveBigIntegerField(blank=True, null=True)),
                ('weight_type', models.CharField(blank=True, max_length=20, null=True)),
                ('steamshiping_line', models.CharField(blank=True, max_length=50, null=True)),
                ('trucking_company_in', models.CharField(blank=True, max_length=20, null=True)),
                ('outer_company_in', models.CharField(blank=True, max_length=20, null=True)),
                ('outer_company_manual_in', models.CharField(blank=True, max_length=20, null=True)),
                ('truck_number_in', models.CharField(blank=True, max_length=20, null=True)),
                ('manual_truck_number_in', models.CharField(blank=True, max_length=20, null=True)),
                ('chassis_number_in', models.CharField(blank=True, max_length=20, null=True)),
                ('prepull_notes', models.CharField(blank=True, max_length=100, null=True)),
                ('comments_in', models.CharField(blank=True, max_length=100, null=True)),
                ('total_days', models.CharField(blank=True, max_length=100, null=True)),
                ('invoice', models.CharField(blank=True, max_length=100, null=True)),
                ('outer_company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='dashboard.truckingcompany')),
                ('truck_number', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='dashboard.truck')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Chassis_Damage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chassis_number', models.IntegerField()),
                ('added_on', models.DateTimeField(auto_now_add=True)),
                ('chassis_problem', models.TextField(blank=True, null=True)),
                ('location', models.CharField(choices=[('coming soon', 'coming soon'), ('on road', 'on road'), ('yard', 'YARD')], max_length=20, null=True)),
                ('tag_number', models.IntegerField(blank=True, null=True)),
                ('assignment', models.CharField(blank=True, max_length=20, null=True)),
                ('dmg_img', models.ImageField(blank=True, default='/chassis_damages/dmg.jpg', null=True, upload_to='chassis_damages')),
                ('eta', models.DateTimeField(blank=True, null=True)),
                ('unit_number', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='dashboard.truck')),
            ],
        ),
    ]
