# Generated by Django 3.2.13 on 2022-08-27 19:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='prepull',
            name='containerType',
        ),
        migrations.RemoveField(
            model_name='prepull',
            name='container_status',
        ),
        migrations.AddField(
            model_name='prepull',
            name='steamshiping_line',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='dashboard.steamship'),
        ),
        migrations.AlterField(
            model_name='container_in_gate',
            name='container_status',
            field=models.CharField(choices=[('load', 'Load'), ('empty', 'Empty'), ('drop', 'DROP'), ('switch', 'SWITCH')], max_length=6),
        ),
    ]
