# Generated by Django 3.2.13 on 2022-09-18 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_auto_20220827_1945'),
    ]

    operations = [
        migrations.AlterField(
            model_name='container_in_gate',
            name='container_status',
            field=models.CharField(choices=[('load', 'Load'), ('empty', 'Empty'), ('drop', 'DROP'), ('switch', 'SWITCH'), ('terminated', 'TERMINATED'), ('storage', 'STORAGE')], max_length=15),
        ),
    ]
